// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to personalize testimonials based on user input.
 *
 * - personalizeTestimonial - A function that generates a personalized testimonial.
 * - PersonalizeTestimonialInput - The input type for the personalizeTestimonial function.
 * - PersonalizeTestimonialOutput - The return type for the personalizeTestimonial function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PersonalizeTestimonialInputSchema = z.object({
  age: z.number().describe('The age of the user.'),
  gender: z.enum(['male', 'female']).describe('The gender of the user.'),
  painLocation: z
    .string()
    .describe('The location of the user\'s back pain (e.g., lower back, upper back).'),
  painLevel: z
    .number()
    .min(1)
    .max(10)
    .describe('The user\'s pain level on a scale of 1 to 10.'),
  activityLevel: z
    .string()
    .describe('The user\'s daily activity level (e.g., sedentary, active).'),
});

export type PersonalizeTestimonialInput = z.infer<
  typeof PersonalizeTestimonialInputSchema
>;

const PersonalizeTestimonialOutputSchema = z.object({
  testimonial: z.string().describe('The personalized testimonial.'),
});

export type PersonalizeTestimonialOutput = z.infer<
  typeof PersonalizeTestimonialOutputSchema
>;

export async function personalizeTestimonial(
  input: PersonalizeTestimonialInput
): Promise<PersonalizeTestimonialOutput> {
  return personalizeTestimonialFlow(input);
}

const prompt = ai.definePrompt({
  name: 'personalizeTestimonialPrompt',
  input: {schema: PersonalizeTestimonialInputSchema},
  output: {schema: PersonalizeTestimonialOutputSchema},
  prompt: `You are a marketing expert tasked with writing a personalized testimonial for an orthopedic posture corrector. The testimonial should be relatable and encourage the potential buyer to purchase the product.

  Consider the following information about the potential buyer:
  - Age: {{{age}}}
  - Gender: {{{gender}}}
  - Pain Location: {{{painLocation}}}
  - Pain Level: {{{painLevel}}}
  - Activity Level: {{{activityLevel}}}

  Write a testimonial that addresses their specific situation and highlights the benefits of using the posture corrector to alleviate their back pain. The testimonial should sound authentic and be no more than three sentences. The testimonial must be in Spanish.

  Testimonial:`,
});

const personalizeTestimonialFlow = ai.defineFlow(
  {
    name: 'personalizeTestimonialFlow',
    inputSchema: PersonalizeTestimonialInputSchema,
    outputSchema: PersonalizeTestimonialOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
